//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.SI;

[assembly: RegisterDocumentType(Home.CLASS_NAME, typeof(Home))]

namespace CMS.DocumentEngine.Types.SI
{
	/// <summary>
	/// Represents a content item of type Home.
	/// </summary>
	public partial class Home : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "SI.Home";


		/// <summary>
		/// The instance of the class that provides extended API for working with Home fields.
		/// </summary>
		private readonly HomeFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// HomeID.
		/// </summary>
		[DatabaseIDField]
		public int HomeID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("HomeID"), 0);
			}
			set
			{
				SetValue("HomeID", value);
			}
		}


		/// <summary>
		/// Banner header.
		/// </summary>
		[DatabaseField]
		public string HomeBannerHeader
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeBannerHeader"), @"");
			}
			set
			{
				SetValue("HomeBannerHeader", value);
			}
		}


		/// <summary>
		/// Banner subtext.
		/// </summary>
		[DatabaseField]
		public string HomeBannerSubtext
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeBannerSubtext"), @"");
			}
			set
			{
				SetValue("HomeBannerSubtext", value);
			}
		}


		/// <summary>
		/// Banner image.
		/// </summary>
		[DatabaseField]
		public Guid HomeBannerImage
		{
			get
			{
				return ValidationHelper.GetGuid(GetValue("HomeBannerImage"), Guid.Empty);
			}
			set
			{
				SetValue("HomeBannerImage", value);
			}
		}


		/// <summary>
		/// Login header.
		/// </summary>
		[DatabaseField]
		public string HomeLoginHeader
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeLoginHeader"), @"");
			}
			set
			{
				SetValue("HomeLoginHeader", value);
			}
		}


		/// <summary>
		/// Login body.
		/// </summary>
		[DatabaseField]
		public string HomeLoginBody
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeLoginBody"), @"");
			}
			set
			{
				SetValue("HomeLoginBody", value);
			}
		}


		/// <summary>
		/// Login button text.
		/// </summary>
		[DatabaseField]
		public string HomeLoginButtonText
		{
			get
			{
				return ValidationHelper.GetString(GetValue("HomeLoginButtonText"), @"");
			}
			set
			{
				SetValue("HomeLoginButtonText", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Home fields.
		/// </summary>
		[RegisterProperty]
		public HomeFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Home fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class HomeFields : AbstractHierarchicalObject<HomeFields>
		{
			/// <summary>
			/// The content item of type Home that is a target of the extended API.
			/// </summary>
			private readonly Home mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="HomeFields" /> class with the specified content item of type Home.
			/// </summary>
			/// <param name="instance">The content item of type Home that is a target of the extended API.</param>
			public HomeFields(Home instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// HomeID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.HomeID;
				}
				set
				{
					mInstance.HomeID = value;
				}
			}


			/// <summary>
			/// Banner header.
			/// </summary>
			public string BannerHeader
			{
				get
				{
					return mInstance.HomeBannerHeader;
				}
				set
				{
					mInstance.HomeBannerHeader = value;
				}
			}


			/// <summary>
			/// Banner subtext.
			/// </summary>
			public string BannerSubtext
			{
				get
				{
					return mInstance.HomeBannerSubtext;
				}
				set
				{
					mInstance.HomeBannerSubtext = value;
				}
			}


			/// <summary>
			/// Banner image.
			/// </summary>
			public DocumentAttachment BannerImage
			{
				get
				{
					return mInstance.GetFieldDocumentAttachment("HomeBannerImage");
				}
			}


			/// <summary>
			/// Login header.
			/// </summary>
			public string LoginHeader
			{
				get
				{
					return mInstance.HomeLoginHeader;
				}
				set
				{
					mInstance.HomeLoginHeader = value;
				}
			}


			/// <summary>
			/// Login body.
			/// </summary>
			public string LoginBody
			{
				get
				{
					return mInstance.HomeLoginBody;
				}
				set
				{
					mInstance.HomeLoginBody = value;
				}
			}


			/// <summary>
			/// Login button text.
			/// </summary>
			public string LoginButtonText
			{
				get
				{
					return mInstance.HomeLoginButtonText;
				}
				set
				{
					mInstance.HomeLoginButtonText = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Home" /> class.
		/// </summary>
		public Home() : base(CLASS_NAME)
		{
			mFields = new HomeFields(this);
		}

		#endregion
	}
}